# a2query
# Autogenerated from man page /usr/share/man/man1/a2query.1.gz
complete -c a2query -s a -d 'Returns the Apache 2 \\*(L"Module Magic Version\\*(R" (\\s-1API\\s0 version) numb…'
complete -c a2query -s c -d 'Checks whether the configuration \\s-1CONF\\s0 is enabled'
complete -c a2query -s h -d 'Displays a brief summary how the program can be called and exits'
complete -c a2query -s m -d 'Checks whether the module \\s-1MODULE\\s0 is enabled, The argument is interpret…'
complete -c a2query -s M -d 'Returns the currently enabled Apache 2 \\s-1MPM\\s0 (Multi Processing Module)'
complete -c a2query -s s -d 'Checks whether the module \\s-1SITE\\s0 is enabled, The argument is interpreted…'
complete -c a2query -s v -d 'returns the currently installed Apache 2 \\s-1HTTP\\s0 server version'

