# bin2obj-3.2.2
# Autogenerated from man page /usr/share/man/man1/bin2obj-3.2.2.1.gz
complete -c 'bin2obj-3.2.2' -s a -d 'Write ASCII data instead of bytes'
complete -c 'bin2obj-3.2.2' -s e -d 'If this option is given, the data will be encrypted with   key which is a str…'
complete -c 'bin2obj-3.2.2' -s h -d 'emit a small helptext'
complete -c 'bin2obj-3.2.2' -s o -d 'By default, the output goes to standard output (the screen)'
complete -c 'bin2obj-3.2.2' -s u -d 'This option tells  bin2obj to generate a unit'
complete -c 'bin2obj-3.2.2' -s U -d 'The same as the  -u option, only bin2obj will also call the compiler and comp…'
complete -c 'bin2obj-3.2.2' -s c -d 'option).  The output goes to standard output by default'
complete -c 'bin2obj-3.2.2' -s z -d 'Compress the data before creating the unit.  zlib compression is used'

