# black-primer
# Autogenerated from man page /usr/share/man/man1/black-primer.1.gz
complete -c black-primer -l check -d 'are configured in primer. json RUN FLOW'
complete -c black-primer -l keep
complete -c black-primer -l - -d '+++ tests/b303_b304. py      2020-05-17 20:06:42'

