# cli-resgen
# Autogenerated from man page /usr/share/man/man1/cli-resgen.1.gz
complete -c cli-resgen -o compile -d 'Sp This switch instructs resgen to compile multiple files'
complete -c cli-resgen -o usesourcepath

