# cli-gacutil
# Autogenerated from man page /usr/share/man/man1/cli-gacutil.1.gz
complete -c cli-gacutil -o package
complete -c cli-gacutil -s i -o root -o gacdir
complete -c cli-gacutil -s l
complete -c cli-gacutil -s u
complete -c cli-gacutil -o us -d 'Uninstalls an assembly using the specified assembly\'s full name'
complete -c cli-gacutil -o ul -d 'Uninstalls one or more assemblies from the global assembly cache'

