# cpplint
# Autogenerated from man page /usr/share/man/man1/cpplint.1.gz
complete -c cpplint -l filter -o whitespace/ -o runtime/printf
complete -c cpplint -s / -d 'To see a list of all the categories used in cpplint, pass no arg:'
complete -c cpplint -l root
complete -c cpplint -l linelength -d 'recursive Search for files to lint recursively'
complete -c cpplint -l exclude
complete -c cpplint -l extensions -d 'includeorder=default|standardcfirst For the build/include_order rule, the def…'
complete -c cpplint -l headers

