# data2inc-3.2.2
# Autogenerated from man page /usr/share/man/man1/data2inc-3.2.2.1.gz
complete -c 'data2inc-3.2.2' -s A -d 'Write bytes instead of characters'
complete -c 'data2inc-3.2.2' -s B -d 'If this option is given, the   msgfile will be treated as a binary file'
complete -c 'data2inc-3.2.2' -s H -d 'emit a small helptext'
complete -c 'data2inc-3.2.2' -s S -d 'data2inc will write the output as an array of strings, or a 2 dimensional arr…'
complete -c 'data2inc-3.2.2' -s V -d 'Show the version number and exit'

