# delp
# Autogenerated from man page /usr/share/man/man1/delp.1.gz
complete -c delp -s e -d 'Delete all executable files as well.  This option has no effect on Linux'
complete -c delp -s h -d 'Displays a short help message'
complete -c delp -s q -d 'Be more quiet.  Normally, delp gives a count of the number of files deleted'

