# fd2pascal-3.2.2
# Autogenerated from man page /usr/share/man/man1/fd2pascal-3.2.2.1.gz
complete -c 'fd2pascal-3.2.2' -o altformat -d 'By default, a record type is emitted for the form definition, with a field fo…'
complete -c 'fd2pascal-3.2.2' -o compensate -d 'If this option is given then a call to fl_adjust_form_size is emitted after t…'
complete -c 'fd2pascal-3.2.2' -o callback -d 'If this option is given, then a callback procedure is generated for each  wid…'
complete -c 'fd2pascal-3.2.2' -o main -d 'By default, a unit is created which can be included in the uses clause of a p…'

