# fpcjres-3.2.2
# Autogenerated from man page /usr/share/man/man1/fpcjres-3.2.2.1.gz
complete -c 'fpcjres-3.2.2' -l help -s h -s '?' -d 'Show a help message screen'
complete -c 'fpcjres-3.2.2' -l version -s V -d 'Show program version'
complete -c 'fpcjres-3.2.2' -l verbose -s v -d 'Be verbose'
complete -c 'fpcjres-3.2.2' -l input -s i -d 'Ignored for compatibility with other tools'
complete -c 'fpcjres-3.2.2' -l output -s o -d 'Set the output file name'

