# fpcmake
# Autogenerated from man page /usr/share/man/man1/fpcmake.1.gz
complete -c fpcmake -s h -d 'Emit a short help text describing the use of  fpcmake'
complete -c fpcmake -s p -d 'If this option is given, a package description file is generated as well as a…'
complete -c fpcmake -s q -d 'Tells   fpcmake to be more quiet, i. e.  emit less messages'
complete -c fpcmake -s r -d 'If this option is given,   fpcmake will recursively scan subdirectories for  …'
complete -c fpcmake -s T -d 'Specifies the targets for which   fpcmake  should generate makefiles'
complete -c fpcmake -s v -d 'This option instructs  fpcmake to be more verbose'
complete -c fpcmake -s V -d 'Print  fpcmake version and exit'
complete -c fpcmake -s w -d 'This is the standard option and tells fpcmake to generate a makefile'

