# fprcp
# Autogenerated from man page /usr/share/man/man1/fprcp.1.gz
complete -c fprcp -s C -d 'Define the symbol   symbol before processing is started'
complete -c fprcp -s i -d 'Specify the input file name.  This argument is mandatory'
complete -c fprcp -s l -d 'Set the programming language for include files'
complete -c fprcp -s n -d 'Do not support nested comments'
complete -c fprcp -s p -d 'Set the include path'

