# fprcp-3.2.2
# Autogenerated from man page /usr/share/man/man1/fprcp-3.2.2.1.gz
complete -c 'fprcp-3.2.2' -s C -d 'Define the symbol   symbol before processing is started'
complete -c 'fprcp-3.2.2' -s i -d 'Specify the input file name.  This argument is mandatory'
complete -c 'fprcp-3.2.2' -s l -d 'Set the programming language for include files'
complete -c 'fprcp-3.2.2' -s n -d 'Do not support nested comments'
complete -c 'fprcp-3.2.2' -s p -d 'Set the include path'

