# gh-codespace-rebuild
# Autogenerated from man page /usr/share/man/man1/gh-codespace-rebuild.1.gz
complete -c gh-codespace-rebuild -s c -l codespace -d 'name of the codespace'
complete -c gh-codespace-rebuild -l full -d 'perform a full rebuild SEE ALSO'

