# h2paspp-3.2.2
# Autogenerated from man page /usr/share/man/man1/h2paspp-3.2.2.1.gz
complete -c 'h2paspp-3.2.2' -o dsymbol -d 'Define the symbol   symbol before processing is started'
complete -c 'h2paspp-3.2.2' -s h -d 'emit a small helptext'
complete -c 'h2paspp-3.2.2' -s I -d 'option was given, in which case the include file is included and written to t…'
complete -c 'h2paspp-3.2.2' -s o -d 'option is given, in which case the file is written to the specified file'
complete -c 'h2paspp-3.2.2' -o ooutfile -d 'If this option is given, the output will be written to a file named outfile'

