# h2pas-3.2.2
# Autogenerated from man page /usr/share/man/man1/h2pas-3.2.2.1.gz
complete -c 'h2pas-3.2.2' -s d -d 'use   external; for all procedure and function declarations'
complete -c 'h2pas-3.2.2' -s D -d 'use   external  libname   name  \'func\\_name\' for function and procedure decla…'
complete -c 'h2pas-3.2.2' -s e -d 'Emit a series of constants instead of an enumeration type for the C   enum co…'
complete -c 'h2pas-3.2.2' -s i -d 'create an include file instead of a unit (omits the unit header)'
complete -c 'h2pas-3.2.2' -s l -d 'specify the library name for external function declarations'
complete -c 'h2pas-3.2.2' -s o -d 'Specify the output file name'
complete -c 'h2pas-3.2.2' -s p -d 'use the letter    P in front of pointer type parameters instead of "^"'
complete -c 'h2pas-3.2.2' -s s -d 'Strip comments from the input file'
complete -c 'h2pas-3.2.2' -s t -d 'prepend typedef type names with the letter  T (used to follow Borland\'s conve…'
complete -c 'h2pas-3.2.2' -s v -d 'replace pointer parameters by call by reference parameters'
complete -c 'h2pas-3.2.2' -s w -d 'Header file is a win32 header file (adds support for some special macros)'
complete -c 'h2pas-3.2.2' -s x -d 'handle SYS_TRAP of the PalmOS header files'

