# h2paspp
# Autogenerated from man page /usr/share/man/man1/h2paspp.1.gz
complete -c h2paspp -o dsymbol -d 'Define the symbol   symbol before processing is started'
complete -c h2paspp -s h -d 'emit a small helptext'
complete -c h2paspp -s I -d 'option was given, in which case the include file is included and written to t…'
complete -c h2paspp -s o -d 'option is given, in which case the file is written to the specified file'
complete -c h2paspp -o ooutfile -d 'If this option is given, the output will be written to a file named outfile'

