# ifpc
# Autogenerated from man page /usr/share/man/man1/ifpc.1.gz
complete -c ifpc -s h -d 'Prints this help message and exit'
complete -c ifpc -s v -d 'Prints version and exit'
complete -c ifpc -l get-cache -d 'Prints current cache directory and exit'
complete -c ifpc -l set-cache -d 'Set the cache to be used'
complete -c ifpc -l compiler -d 'Normally fpc is searched in PATH and used as compiler'
complete -c ifpc -l skip-run -d 'Do not execute the program.  Useful to test if script compiles'
complete -c ifpc -s B -d 'Always recompile'

