# ifpc-3.2.2
# Autogenerated from man page /usr/share/man/man1/ifpc-3.2.2.1.gz
complete -c 'ifpc-3.2.2' -s h -d 'Prints this help message and exit'
complete -c 'ifpc-3.2.2' -s v -d 'Prints version and exit'
complete -c 'ifpc-3.2.2' -l get-cache -d 'Prints current cache directory and exit'
complete -c 'ifpc-3.2.2' -l set-cache -d 'Set the cache to be used'
complete -c 'ifpc-3.2.2' -l compiler -d 'Normally fpc is searched in PATH and used as compiler'
complete -c 'ifpc-3.2.2' -l skip-run -d 'Do not execute the program.  Useful to test if script compiles'
complete -c 'ifpc-3.2.2' -s B -d 'Always recompile'

