# instantfpc
# Autogenerated from man page /usr/share/man/man1/instantfpc.1.gz
complete -c instantfpc -s h -d 'Prints this help message and exit'
complete -c instantfpc -s v -d 'Prints version and exit'
complete -c instantfpc -l get-cache -d 'Prints current cache directory and exit'
complete -c instantfpc -l set-cache -d 'Set the cache to be used'
complete -c instantfpc -l compiler -d 'Normally fpc is searched in PATH and used as compiler'
complete -c instantfpc -l skip-run -d 'Do not execute the program.  Useful to test if script compiles'
complete -c instantfpc -s B -d 'Always recompile'

