# monop2
# Autogenerated from man page /usr/share/man/man1/monop2.1.gz
complete -c monop2 -o r:assembly -d 'Specifies the assembly to use for looking up the type'
complete -c monop2 -s a -d 'Renders all of the types in the specified assembly'
complete -c monop2 -l search -s s -s k -d 'Searches through all known assemblies for types containing `class\''
complete -c monop2 -l refs -d 'Prints a list of the referenced assemblies for an assembly'
complete -c monop2 -l filter-obsolete -s f -d 'Do not show obsolete types and members'
complete -c monop2 -l declared-only -s d -d 'Only show members declared in the type'
complete -c monop2 -l private -s p -d 'Show private members'
complete -c monop2 -l runtime-version -d 'Print runtime version'
complete -c monop2 -o xa -d 'Sets the lookup path to the Xamarin. Android directory'
complete -c monop2 -o xi -d 'Sets the lookup path to the Xamarin. iOS directory'

