# pas2fpm-3.2.2
# Autogenerated from man page /usr/share/man/man1/pas2fpm-3.2.2.1.gz
complete -c 'pas2fpm-3.2.2' -s h -d 'Displays a short help message'
complete -c 'pas2fpm-3.2.2' -s o -d 'By default,  pas2fpm writes a file  fpmake'
complete -c 'pas2fpm-3.2.2' -s p -d 'Specify the name for the package in the fpmake file'
complete -c 'pas2fpm-3.2.2' -s v -d 'Be verbose: write some diagnostic output'

