# pas2jni-3.2.2
# Autogenerated from man page /usr/share/man/man1/pas2jni-3.2.2.1.gz
complete -c 'pas2jni-3.2.2' -o 'U<path>' -d 'Unit search path, semicolon delimited.  Wildcards are allowed'
complete -c 'pas2jni-3.2.2' -o 'L<name>' -d 'Set output library name'
complete -c 'pas2jni-3.2.2' -o 'P<name>' -d 'Set Java package name.  This is by default \'pas\''
complete -c 'pas2jni-3.2.2' -o 'O<path>' -d 'Set output path for Pascal files.  This is the current directory, by default'
complete -c 'pas2jni-3.2.2' -o 'J<path>' -d 'Set output path for Java files.  By default, this is \'pas\''
complete -c 'pas2jni-3.2.2' -o 'D<prog>' -d 'Set full path to the "ppudump" program'
complete -c 'pas2jni-3.2.2' -o 'I<list>' -d 'Include the list of specified objects in the output'
complete -c 'pas2jni-3.2.2' -s E -d 'Exclude the list of specified objects from the output'
complete -c 'pas2jni-3.2.2' -s '?' -d 'Show a help message.  EXAMPLES The following will create a file pas/getopts'

