# php8.2
# Autogenerated from man page /usr/share/man/man1/php8.2.1.gz
complete -c 'php8.2' -s a -d 'Run PHP interactively'
complete -c 'php8.2' -s b -d 'Bind Path for external FASTCGI Server mode (CGI only)'
complete -c 'php8.2' -s C -d 'Do not chdir to the script\'s directory (CGI only)'
complete -c 'php8.2' -s q -d 'Quiet-mode.  Suppress HTTP header output (CGI only)'
complete -c 'php8.2' -s T -d 'Measure execution time of script repeated count times (CGI only)'
complete -c 'php8.2' -s c -d 'Look for  php. ini file in the directory R path or use the specified R file'
complete -c 'php8.2' -s n -d 'No  php. ini file will be used'
complete -c 'php8.2' -s d -d 'Define INI entry R foo with value R bar'
complete -c 'php8.2' -s e -d 'Generate extended information for debugger/profiler'
complete -c 'php8.2' -s f -d 'Parse and execute R file'
complete -c 'php8.2' -s h -d 'This help'
complete -c 'php8.2' -s H -d 'Hide script name (file) and parameters (args. ) from external tools'
complete -c 'php8.2' -s i -d 'PHP information and configuration'
complete -c 'php8.2' -s l -d 'Syntax check only (lint)'
complete -c 'php8.2' -s m -d 'Show compiled in modules'
complete -c 'php8.2' -s r -d 'Run PHP R code without using script tags  \'<?. ?>\''
complete -c 'php8.2' -s B -d 'Run PHP R begin_code before processing input lines'
complete -c 'php8.2' -s R -d 'Run PHP R code for every input line'
complete -c 'php8.2' -s F -d 'Parse and execute R file for every input line'
complete -c 'php8.2' -s E -d 'Run PHP R end_code after processing all input lines'
complete -c 'php8.2' -s s -d 'Output HTML syntax highlighted source'
complete -c 'php8.2' -s S -d 'Start built-in web server on the given local address and port'
complete -c 'php8.2' -s t -d 'Specify the document root to be used by the built-in web server'
complete -c 'php8.2' -s v -d 'Version number'
complete -c 'php8.2' -s w -d 'Output source with stripped comments and whitespace'
complete -c 'php8.2' -s z -d 'Load Zend extension R file'
complete -c 'php8.2' -l rfunction -d 'R name'
complete -c 'php8.2' -l rf -d 'R name Shows information about function  name'
complete -c 'php8.2' -l rclass -d 'R name'
complete -c 'php8.2' -l rc -d 'R name Shows information about class  name'
complete -c 'php8.2' -l rextension -d 'R name'
complete -c 'php8.2' -l re -d 'R name Shows information about extension  name'
complete -c 'php8.2' -l rzendextension -d 'R name'
complete -c 'php8.2' -l rz -d 'R name Shows information about Zend extension  name'
complete -c 'php8.2' -l rextinfo -d 'R name'
complete -c 'php8.2' -l ri -d 'R name Shows configuration for extension  name'
complete -c 'php8.2' -l interactive
complete -c 'php8.2' -l bindpath
complete -c 'php8.2' -l no-chdir
complete -c 'php8.2' -l no-header
complete -c 'php8.2' -l timing
complete -c 'php8.2' -l php-ini
complete -c 'php8.2' -l no-php-ini
complete -c 'php8.2' -l define
complete -c 'php8.2' -l file
complete -c 'php8.2' -l help
complete -c 'php8.2' -l hide-args
complete -c 'php8.2' -l info
complete -c 'php8.2' -l syntax-check
complete -c 'php8.2' -l modules
complete -c 'php8.2' -l run
complete -c 'php8.2' -l process-begin
complete -c 'php8.2' -l process-code
complete -c 'php8.2' -l process-file
complete -c 'php8.2' -l process-end
complete -c 'php8.2' -l syntax-highlight
complete -c 'php8.2' -l server
complete -c 'php8.2' -l docroot
complete -c 'php8.2' -l version
complete -c 'php8.2' -l strip
complete -c 'php8.2' -l zend-extension
complete -c 'php8.2' -l ini -d 'Show configuration file names FILES'

