# pkcs11-register
# Autogenerated from man page /usr/share/man/man1/pkcs11-register.1.gz
complete -c pkcs11-register -l help -s h -d 'Print help message on screen'
complete -c pkcs11-register -l version -s V -d 'Print the OpenSC package release version'
complete -c pkcs11-register -l module -s m -d 'Path to the PKCS#11 module to load.  The default is OpenSC PKCS#11 module'
complete -c pkcs11-register -l skip-chrome -d 'Don\\*(Aqt install module for Chrome browser'
complete -c pkcs11-register -l skip-firefox -d 'Don\\*(Aqt install module for Firefox browser'
complete -c pkcs11-register -l skip-thunderbird -d 'Don\\*(Aqt install module for Thunderbird mail client'
complete -c pkcs11-register -l skip-seamonkey -d 'Don\\*(Aqt install module for Seamonkey'

