# plex-3.2.2
# Autogenerated from man page /usr/share/man/man1/plex-3.2.2.1.gz
complete -c 'plex-3.2.2' -s v -d 'Verbose:  plex generates a readable description of the generated lexical anal…'
complete -c 'plex-3.2.2' -s o -d 'Optimize: plex optimizes DFA tables to produce a minimal DFA'

