# plex
# Autogenerated from man page /usr/share/man/man1/plex.1.gz
complete -c plex -s v -d 'Verbose:  plex generates a readable description of the generated lexical anal…'
complete -c plex -s o -d 'Optimize: plex optimizes DFA tables to produce a minimal DFA'

