# postw32
# Autogenerated from man page /usr/share/man/man1/postw32.1.gz
complete -c postw32 -s i -d 'specifies the input file to process'
complete -c postw32 -s h -d 'Displays a short help message'
complete -c postw32 -s m -d 'Set the subsystem (the application type) to either   gui or  console'
complete -c postw32 -s s -d 'Set the stack size to   size bytes'
complete -c postw32 -s v -d 'Be verbose about the operations that are performed'
complete -c postw32 -l input -d option
complete -c postw32 -l help -d option
complete -c postw32 -l subsystem -d option
complete -c postw32 -l stack -d option
complete -c postw32 -l verbose -d option
complete -c postw32 -s V -d 'Set the version of the file to  M'
complete -c postw32 -l version -d 'option.  SEE ALSO fpc (1) ppc386 (1)'

