# postw32-3.2.2
# Autogenerated from man page /usr/share/man/man1/postw32-3.2.2.1.gz
complete -c 'postw32-3.2.2' -s i -d 'specifies the input file to process'
complete -c 'postw32-3.2.2' -s h -d 'Displays a short help message'
complete -c 'postw32-3.2.2' -s m -d 'Set the subsystem (the application type) to either   gui or  console'
complete -c 'postw32-3.2.2' -s s -d 'Set the stack size to   size bytes'
complete -c 'postw32-3.2.2' -s v -d 'Be verbose about the operations that are performed'
complete -c 'postw32-3.2.2' -l input -d option
complete -c 'postw32-3.2.2' -l help -d option
complete -c 'postw32-3.2.2' -l subsystem -d option
complete -c 'postw32-3.2.2' -l stack -d option
complete -c 'postw32-3.2.2' -l verbose -d option
complete -c 'postw32-3.2.2' -s V -d 'Set the version of the file to  M'
complete -c 'postw32-3.2.2' -l version -d 'option.  SEE ALSO fpc (1) ppc386 (1)'

