# resgen2
# Autogenerated from man page /usr/share/man/man1/resgen2.1.gz
complete -c resgen2 -o compile -d 'Sp This switch instructs resgen to compile multiple files'
complete -c resgen2 -o usesourcepath

