# rstconv-3.2.2
# Autogenerated from man page /usr/share/man/man1/rstconv-3.2.2.1.gz
complete -c 'rstconv-3.2.2' -s f -d 'Specify the output file format'
complete -c 'rstconv-3.2.2' -s h -l help -d 'outputs a short help message'
complete -c 'rstconv-3.2.2' -s i -d 'Specifies the input file name.  If omitted, then standard input is assumed'
complete -c 'rstconv-3.2.2' -s o -d 'to specify the output file name'

