# rstconv
# Autogenerated from man page /usr/share/man/man1/rstconv.1.gz
complete -c rstconv -s f -d 'Specify the output file format'
complete -c rstconv -s h -l help -d 'outputs a short help message'
complete -c rstconv -s i -d 'Specifies the input file name.  If omitted, then standard input is assumed'
complete -c rstconv -s o -d 'to specify the output file name'

