# sdl-config
# Autogenerated from man page /usr/share/man/man1/sdl-config.1.gz
complete -c sdl-config -l cflags -d 'Print the compiler flags that are necessary to compile a program or library t…'
complete -c sdl-config -l exec-prefix -d 'If DIR is not specified, print the exec prefix of the current SDL installation'
complete -c sdl-config -l libs -d 'Print the linker flags that are necessary to link a program that uses SDL'
complete -c sdl-config -l static-libs -d 'Print the linker flags that are necessary to statically link a program that u…'
complete -c sdl-config -l prefix -d 'If DIR is not specified, print the prefix of the current SDL installation'
complete -c sdl-config -l version -d 'Prints the currently installed version of SDL on standard output.  EXAMPLES'

