# vhs
# Autogenerated from man page /usr/share/man/man1/vhs.1.gz
complete -c vhs -s o -l output -d 'file name(s) of video output'
complete -c vhs -s p -l publish -d 'publish your GIF to vhs. charm. sh and get a shareable URL'
complete -c vhs -s q -l quiet -d 'quiet do not log messages'
complete -c vhs -s s -l shell -d 'shell for recording serve'
complete -c vhs -l markdown -d 'output as markdown validate <file>'

